[tool.typeo.base]
channels = [
    "H1:GDS-CALIB_STRAIN",
    "H1:PEM-CS_MAINSMON_EBAY_1_DQ",
    "H1:ASC-INP1_P_INMON",
    "H1:ASC-INP1_Y_INMON",
    "H1:ASC-MICH_P_INMON",
    "H1:ASC-MICH_Y_INMON",
    "H1:ASC-PRC1_P_INMON",
    "H1:ASC-PRC1_Y_INMON",
    "H1:ASC-PRC2_P_INMON",
    "H1:ASC-PRC2_Y_INMON",
    "H1:ASC-SRC1_P_INMON",
    "H1:ASC-SRC1_Y_INMON",
    "H1:ASC-SRC2_P_INMON",
    "H1:ASC-SRC2_Y_INMON",
    "H1:ASC-DHARD_P_INMON",
    "H1:ASC-DHARD_Y_INMON",
    "H1:ASC-CHARD_P_INMON",
    "H1:ASC-CHARD_Y_INMON",
    "H1:ASC-DSOFT_P_INMON",
    "H1:ASC-DSOFT_Y_INMON",
    "H1:ASC-CSOFT_P_INMON",
    "H1:ASC-CSOFT_Y_INMON"
]
sample_rate = 4096
output_directory = "../results/test"
train_t0 = 1238292996
train_duration = 2000
verbose = false

max_latency = 0.5
infer_kernel_length = 1
infer_kernel_stride = 0.001953125

# we can leave the autoencoder args empty because
# it doesn't take any arguments except input shape
autoencoder = {}

[tool.typeo.scripts.train]
channels = "${base.channels}"
output_directory = "${base.output_directory}"
sample_rate = "${base.sample_rate}"
t0 = "${base.train_t0}"
duration = "${base.train_duration}"

# TODO: add typeo fix which allows multiple wildcards
# and then replace this 2000 with "${base.train_duration}"
data_directory = "data/${base.train_t0}/2000"
valid_frac = 0.25

kernel_length = 8
kernel_stride = 0.25
chunk_length = 0

filt_fl = 55.0
filt_fh = 65.0
filt_order = 8

batch_size = 32
max_epochs = 200
lr = 3.2e-2
weight_decay = 1e-5
patience = 40
factor = 0.2
early_stop = 100

fftlength = 2
overlap = 1
alpha = 1.0

device = "cuda"
profile = false
verbose = "${base.verbose}"
commands.autoencoder = "${base.autoencoder}"

[tool.typeo.scripts.export]
repository_directory = "../repo"
channels = "${base.channels}"
weights = "${base.output_directory}"
kernel_length = "${base.infer_kernel_length}"
stride_length = "${base.infer_kernel_stride}"
sample_rate = "${base.sample_rate}"
max_latency = "${base.max_latency}"
instances = 6
verbose = "${base.verbose}"
commands.autoencoder = "${base.autoencoder}"

[tool.typeo.scripts.infer]
url = "localhost:8001"
model_name = "deepclean-stream-0.5"
train_directory = "${base.output_directory}"

witness_data_dir = "${DATA_DIR}/lldetchar/H1"
strain_data_dir = "${DATA_DIR}/llhoft/H1"
channels = "${base.channels}"
kernel_length = "${base.infer_kernel_length}"
stride_length = "${base.infer_kernel_stride}"
sample_rate = "${base.sample_rate}"

max_latency = "${base.max_latency}"
filter_memory = 10
filter_lead_time = 0.5

max_frames = 50
sequence_id = 1001
verbose = true

[tool.typeo.scripts.analyze]
raw_data_dir = "${DATA_DIR}/llhoft/H1"
clean_data_dir = "${base.output_directory}/cleaned"
output_directory = "${base.output_directory}"
channels = "${base.channels}"
sample_rate = "${base.sample_rate}"
fftlength = 10

# TODO: move the values from training
# to base and do these there
freq_low = 55
freq_high = 65
